package export

import (
	"fmt"
	"strings"

	"github.com/scaleforge/scaleforge/internal/agentflow"
)

// genGo emits a self-contained, stdlib-only Go program that runs the workflow:
// it executes the nodes in topological order over a small state struct and calls
// an OpenAI-compatible (Groq) endpoint for LLM steps. "Design here, run in Go" —
// it compiles and runs with just GROQ_API_KEY, no third-party modules.
func genGo(cat *agentflow.Catalog, wf agentflow.Workflow) string {
	defs := cat.Map()
	g := wf.Graph

	hasLLM := false
	for _, n := range g.Nodes {
		if n.Type == agentflow.TypeLLM {
			hasLLM = true
			break
		}
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// %s\n", orEmpty(wf.Name, "Agentic workflow"))
	b.WriteString("// Generated by ScaleForge Agent Studio. Run: GROQ_API_KEY=... go run agent.go\n")
	b.WriteString("package main\n\n")

	b.WriteString("import (\n")
	b.WriteString("\t\"fmt\"\n")
	if hasLLM {
		b.WriteString("\t\"bytes\"\n\t\"encoding/json\"\n\t\"io\"\n\t\"net/http\"\n\t\"os\"\n")
	}
	b.WriteString(")\n\n")

	b.WriteString("type state struct {\n\tQuery   string\n\tContext string\n\tAnswer  string\n}\n\n")

	if hasLLM {
		b.WriteString(goLLMHelper)
	}

	b.WriteString("func main() {\n")
	b.WriteString("\tst := &state{Query: \"Hello, what can you do?\"}\n\n")
	for _, n := range orderedNodes(g) {
		switch n.Type {
		case agentflow.TypeLLM:
			model := orEmpty(n.Config.Model, defs[n.Type].DefaultConfig.Model)
			prompt := orEmpty(n.Config.Prompt, defs[n.Type].DefaultConfig.Prompt)
			fmt.Fprintf(&b, "\t// %s\n", displayLabel(n))
			fmt.Fprintf(&b, "\t{\n\t\tans, err := callLLM(%q, %q, st.Context+\"\\n\\n\"+st.Query)\n", model, prompt)
			b.WriteString("\t\tif err != nil {\n\t\t\tfmt.Println(\"llm error:\", err)\n\t\t\treturn\n\t\t}\n")
			b.WriteString("\t\tst.Answer = ans\n\t}\n\n")
		case agentflow.TypeRetriever:
			fmt.Fprintf(&b, "\t// %s — index=%s quantization=%s topK=%d (plug your vector store)\n",
				displayLabel(n), n.Config.IndexType, n.Config.Quantization, n.Config.TopK)
			b.WriteString("\t// st.Context = retrieve(st.Query)\n\n")
		case agentflow.TypeTool:
			fmt.Fprintf(&b, "\t// %s — tool %q (implement your call)\n\n", displayLabel(n), orEmpty(n.Config.ToolName, "tool"))
		case agentflow.TypeRouter:
			fmt.Fprintf(&b, "\t// Router %q on %q — branch as needed\n\n", displayLabel(n), orEmpty(n.Config.Condition, "condition"))
		default:
			fmt.Fprintf(&b, "\t// %s (%s) — passthrough\n\n", displayLabel(n), n.Type)
		}
	}
	b.WriteString("\tfmt.Println(st.Answer)\n")
	b.WriteString("}\n")
	return b.String()
}

// goLLMHelper is the fixed, stdlib-only Groq client embedded in exported Go.
const goLLMHelper = `func callLLM(model, system, user string) (string, error) {
	body, _ := json.Marshal(map[string]any{
		"model": model,
		"messages": []map[string]string{
			{"role": "system", "content": system},
			{"role": "user", "content": user},
		},
	})
	req, _ := http.NewRequest("POST", "https://api.groq.com/openai/v1/chat/completions", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+os.Getenv("GROQ_API_KEY"))
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	raw, _ := io.ReadAll(resp.Body)
	var out struct {
		Choices []struct {
			Message struct {
				Content string ` + "`json:\"content\"`" + `
			} ` + "`json:\"message\"`" + `
		} ` + "`json:\"choices\"`" + `
	}
	if err := json.Unmarshal(raw, &out); err != nil {
		return "", err
	}
	if len(out.Choices) == 0 {
		return "", fmt.Errorf("no choices: %s", raw)
	}
	return out.Choices[0].Message.Content, nil
}

`
