package export

import (
	"fmt"
	"strings"

	"github.com/scaleforge/scaleforge/internal/agentflow"
)

// genLangGraph emits a runnable LangGraph StateGraph scaffold: a shared State, one
// node function per workflow node (LLM nodes carry the real prompt, retriever/tool
// nodes are stubbed with the configured settings), edges mirroring the design, and
// conditional edges for routers. The user supplies an API key and fills the
// retriever/tool stubs.
func genLangGraph(cat *agentflow.Catalog, wf agentflow.Workflow) string {
	defs := cat.Map()
	g := wf.Graph
	var b strings.Builder

	b.WriteString(`"""` + "\n")
	fmt.Fprintf(&b, "%s\n\n", orEmpty(wf.Name, "Agentic workflow"))
	b.WriteString("Generated by ScaleForge Agent Studio for LangGraph.\n")
	b.WriteString("Install:  pip install langgraph langchain-groq\n")
	b.WriteString("Run:      GROQ_API_KEY=... python agent_langgraph.py\n")
	b.WriteString(`"""` + "\n\n")

	b.WriteString("import os\n")
	b.WriteString("from typing import TypedDict\n")
	b.WriteString("from langgraph.graph import StateGraph, START, END\n")
	b.WriteString("from langchain_groq import ChatGroq\n\n\n")

	b.WriteString("class State(TypedDict, total=False):\n")
	b.WriteString("    query: str       # the user input\n")
	b.WriteString("    context: str     # retrieved documents\n")
	b.WriteString("    answer: str      # the model's response\n\n\n")

	// One function per node.
	for _, n := range orderedNodes(g) {
		fn := ident("node", n.ID)
		switch n.Type {
		case agentflow.TypeLLM:
			model := orEmpty(n.Config.Model, defs[n.Type].DefaultConfig.Model)
			prompt := orEmpty(n.Config.Prompt, defs[n.Type].DefaultConfig.Prompt)
			fmt.Fprintf(&b, "def %s(state: State) -> dict:\n", fn)
			fmt.Fprintf(&b, "    # %s\n", displayLabel(n))
			fmt.Fprintf(&b, "    llm = ChatGroq(model=%q, temperature=%.2f)\n", model, n.Config.Temperature)
			fmt.Fprintf(&b, "    system = %s\n", pyTriple(prompt))
			b.WriteString("    user = state.get(\"query\", \"\")\n")
			b.WriteString("    context = state.get(\"context\", \"\")\n")
			b.WriteString("    messages = [(\"system\", system), (\"human\", f\"{context}\\n\\n{user}\")]\n")
			b.WriteString("    resp = llm.invoke(messages)\n")
			b.WriteString("    return {\"answer\": resp.content}\n\n\n")
		case agentflow.TypeRetriever:
			fmt.Fprintf(&b, "def %s(state: State) -> dict:\n", fn)
			fmt.Fprintf(&b, "    # %s — index=%s quantization=%s top_k=%d dim=%d\n",
				displayLabel(n), n.Config.IndexType, n.Config.Quantization, n.Config.TopK, n.Config.Dim)
			b.WriteString("    # TODO: plug your vector store (FAISS/Chroma/pgvector). Returns context text.\n")
			b.WriteString("    docs = []  # retriever.similarity_search(state[\"query\"], k=%d)\n")
			b.WriteString("    return {\"context\": \"\\n\".join(docs)}\n\n\n")
		case agentflow.TypeTool:
			fmt.Fprintf(&b, "def %s(state: State) -> dict:\n", fn)
			fmt.Fprintf(&b, "    # %s — tool %q, args schema:\n", displayLabel(n), orEmpty(n.Config.ToolName, "tool"))
			fmt.Fprintf(&b, "    # %s\n", orEmpty(n.Config.ToolSchema, "{}"))
			b.WriteString("    # TODO: call your tool/function here.\n")
			b.WriteString("    return {}\n\n\n")
		case agentflow.TypeRouter:
			// Router functions are emitted separately (as conditional edges) below.
			continue
		default:
			fmt.Fprintf(&b, "def %s(state: State) -> dict:\n", fn)
			fmt.Fprintf(&b, "    # %s (%s) — passthrough\n", displayLabel(n), n.Type)
			b.WriteString("    return {}\n\n\n")
		}
	}

	// Router decision functions.
	for _, n := range g.Nodes {
		if n.Type != agentflow.TypeRouter {
			continue
		}
		succ := successors(g, n.ID)
		fmt.Fprintf(&b, "def %s(state: State) -> str:\n", ident("route", n.ID))
		fmt.Fprintf(&b, "    # Router %q on condition: %s\n", displayLabel(n), orEmpty(n.Config.Condition, "condition"))
		b.WriteString("    # TODO: return one of the branch keys below based on state.\n")
		if len(succ) > 0 {
			fmt.Fprintf(&b, "    return %q\n\n\n", branchKey(succ[0]))
		} else {
			b.WriteString("    return \"END\"\n\n\n")
		}
	}

	// Assemble the graph.
	b.WriteString("builder = StateGraph(State)\n")
	for _, n := range g.Nodes {
		if n.Type == agentflow.TypeRouter {
			continue // routers are pure edges, not nodes, in this scaffold
		}
		fmt.Fprintf(&b, "builder.add_node(%q, %s)\n", n.ID, ident("node", n.ID))
	}
	b.WriteString("\n")

	// START → roots.
	for _, n := range roots(g) {
		fmt.Fprintf(&b, "builder.add_edge(START, %q)\n", n.ID)
	}
	// Edges (skip those out of routers; handled as conditional edges).
	for _, e := range g.Edges {
		src, _ := nodeByID(g, e.Source)
		if src.Type == agentflow.TypeRouter {
			continue
		}
		dst, _ := nodeByID(g, e.Target)
		if dst.Type == agentflow.TypeRouter {
			// Edge into a router: wire the conditional edges from the router's source.
			continue
		}
		fmt.Fprintf(&b, "builder.add_edge(%q, %q)\n", e.Source, e.Target)
	}
	// Conditional edges for routers.
	for _, n := range g.Nodes {
		if n.Type != agentflow.TypeRouter {
			continue
		}
		succ := successors(g, n.ID)
		if len(succ) == 0 {
			continue
		}
		// Find the node feeding the router and branch from it.
		var feeder string
		for _, e := range g.Edges {
			if e.Target == n.ID {
				feeder = e.Source
				break
			}
		}
		if feeder == "" {
			feeder = n.ID
		}
		var pairs []string
		for _, e := range succ {
			pairs = append(pairs, fmt.Sprintf("%q: %q", branchKey(e), e.Target))
		}
		fmt.Fprintf(&b, "builder.add_conditional_edges(%q, %s, {%s})\n", feeder, ident("route", n.ID), strings.Join(pairs, ", "))
	}
	// Sinks → END.
	for _, n := range sinks(g) {
		fmt.Fprintf(&b, "builder.add_edge(%q, END)\n", n.ID)
	}

	b.WriteString("\ngraph = builder.compile()\n\n")
	b.WriteString("if __name__ == \"__main__\":\n")
	b.WriteString("    assert os.environ.get(\"GROQ_API_KEY\"), \"set GROQ_API_KEY\"\n")
	b.WriteString("    result = graph.invoke({\"query\": \"Hello, what can you do?\"})\n")
	b.WriteString("    print(result.get(\"answer\", result))\n")
	return b.String()
}

// branchKey is the conditional-edge key for an edge: its label if set, else the
// target id.
func branchKey(e agentflow.Edge) string {
	if e.Label != "" {
		return e.Label
	}
	return e.Target
}

// roots / sinks return nodes with no incoming / no outgoing edges.
func roots(g agentflow.Graph) []agentflow.Node {
	hasIn := make(map[string]bool)
	for _, e := range g.Edges {
		hasIn[e.Target] = true
	}
	var out []agentflow.Node
	for _, n := range g.Nodes {
		if !hasIn[n.ID] && n.Type != agentflow.TypeRouter {
			out = append(out, n)
		}
	}
	return out
}

func sinks(g agentflow.Graph) []agentflow.Node {
	hasOut := make(map[string]bool)
	for _, e := range g.Edges {
		hasOut[e.Source] = true
	}
	var out []agentflow.Node
	for _, n := range g.Nodes {
		if !hasOut[n.ID] && n.Type != agentflow.TypeRouter {
			out = append(out, n)
		}
	}
	return out
}

// pyTriple renders a Python triple-quoted string literal, escaping any embedded
// triple-quote so the generated source stays valid.
func pyTriple(s string) string {
	s = strings.ReplaceAll(s, `"""`, `\"\"\"`)
	return `"""` + s + `"""`
}
