package export

import (
	"fmt"
	"strings"

	"github.com/scaleforge/scaleforge/internal/agentflow"
)

// genLangChain emits a LangChain script: a procedural run(query) that executes the
// nodes in topological order over a state dict, building LCEL prompt|llm chains for
// LLM steps and stubbing retriever/tool steps with their configured settings. It
// favours a readable, runnable trace over a single opaque LCEL expression so
// branching (routers) stays explicit.
func genLangChain(cat *agentflow.Catalog, wf agentflow.Workflow) string {
	defs := cat.Map()
	g := wf.Graph
	var b strings.Builder

	b.WriteString(`"""` + "\n")
	fmt.Fprintf(&b, "%s\n\n", orEmpty(wf.Name, "Agentic workflow"))
	b.WriteString("Generated by ScaleForge Agent Studio for LangChain.\n")
	b.WriteString("Install:  pip install langchain langchain-groq\n")
	b.WriteString("Run:      GROQ_API_KEY=... python agent_langchain.py\n")
	b.WriteString(`"""` + "\n\n")

	b.WriteString("import os\n")
	b.WriteString("from langchain_groq import ChatGroq\n")
	b.WriteString("from langchain_core.prompts import ChatPromptTemplate\n")
	b.WriteString("from langchain_core.output_parsers import StrOutputParser\n\n\n")

	b.WriteString("def run(query: str) -> str:\n")
	b.WriteString("    state = {\"query\": query, \"context\": \"\", \"answer\": \"\"}\n\n")

	for _, n := range orderedNodes(g) {
		switch n.Type {
		case agentflow.TypeLLM:
			model := orEmpty(n.Config.Model, defs[n.Type].DefaultConfig.Model)
			prompt := orEmpty(n.Config.Prompt, defs[n.Type].DefaultConfig.Prompt)
			fmt.Fprintf(&b, "    # %s\n", displayLabel(n))
			fmt.Fprintf(&b, "    llm = ChatGroq(model=%q, temperature=%.2f)\n", model, n.Config.Temperature)
			fmt.Fprintf(&b, "    prompt = ChatPromptTemplate.from_messages([(\"system\", %s), (\"human\", \"{context}\\n\\n{query}\")])\n", pyTriple(prompt))
			b.WriteString("    chain = prompt | llm | StrOutputParser()\n")
			b.WriteString("    state[\"answer\"] = chain.invoke({\"context\": state[\"context\"], \"query\": state[\"query\"]})\n\n")
		case agentflow.TypeRetriever:
			fmt.Fprintf(&b, "    # %s — index=%s quantization=%s top_k=%d\n",
				displayLabel(n), n.Config.IndexType, n.Config.Quantization, n.Config.TopK)
			b.WriteString("    # TODO: retriever = FAISS.load_local(...).as_retriever(search_kwargs={\"k\": " + fmt.Sprintf("%d", n.Config.TopK) + "})\n")
			b.WriteString("    # state[\"context\"] = \"\\n\".join(d.page_content for d in retriever.invoke(state[\"query\"]))\n\n")
		case agentflow.TypeTool:
			fmt.Fprintf(&b, "    # %s — tool %q schema: %s\n", displayLabel(n), orEmpty(n.Config.ToolName, "tool"), orEmpty(n.Config.ToolSchema, "{}"))
			b.WriteString("    # TODO: state.update(call_tool(state))\n\n")
		case agentflow.TypeRouter:
			fmt.Fprintf(&b, "    # Router %q on %q — branch in code as needed.\n\n", displayLabel(n), orEmpty(n.Config.Condition, "condition"))
		default:
			fmt.Fprintf(&b, "    # %s (%s) — passthrough\n\n", displayLabel(n), n.Type)
		}
	}

	b.WriteString("    return state[\"answer\"]\n\n\n")
	b.WriteString("if __name__ == \"__main__\":\n")
	b.WriteString("    assert os.environ.get(\"GROQ_API_KEY\"), \"set GROQ_API_KEY\"\n")
	b.WriteString("    print(run(\"Hello, what can you do?\"))\n")
	return b.String()
}
