package export

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/scaleforge/scaleforge/internal/agentflow"
)

// Mermaid renders the workflow as a Mermaid flowchart — the per-workflow
// architecture diagram that ships with every export and powers the in-app diagram
// view. Node shape encodes role; edge labels carry router branch names.
func Mermaid(wf agentflow.Workflow) string {
	var b strings.Builder
	b.WriteString("flowchart TD\n")
	for _, n := range wf.Graph.Nodes {
		open, close := nodeShape(n.Type)
		label := escapeMermaid(displayLabel(n))
		fmt.Fprintf(&b, "    %s%s\"%s<br/><i>%s</i>\"%s\n", ident("n", n.ID), open, label, n.Type, close)
	}
	b.WriteString("\n")
	for _, e := range wf.Graph.Edges {
		if e.Label != "" {
			fmt.Fprintf(&b, "    %s -->|%s| %s\n", ident("n", e.Source), escapeMermaid(e.Label), ident("n", e.Target))
		} else {
			fmt.Fprintf(&b, "    %s --> %s\n", ident("n", e.Source), ident("n", e.Target))
		}
	}
	return b.String()
}

// nodeShape picks Mermaid bracket pairs so the diagram reads at a glance:
// stadium for IO, hexagon for control, subroutine for retrieval, default box.
func nodeShape(typ string) (open, close string) {
	switch typ {
	case agentflow.TypeInput, agentflow.TypeOutput:
		return "([", "])"
	case agentflow.TypeRouter, agentflow.TypeLoop, agentflow.TypeAggregator:
		return "{{", "}}"
	case agentflow.TypeRetriever, agentflow.TypeEmbedder:
		return "[[", "]]"
	case agentflow.TypeGuardrail:
		return ">", "]"
	default:
		return "[", "]"
	}
}

func escapeMermaid(s string) string {
	s = strings.ReplaceAll(s, "\"", "'")
	return strings.ReplaceAll(s, "\n", " ")
}

// genWorkflowJSON emits a clean, framework-agnostic spec (the graph + metadata)
// that any importer — or a future ScaleForge import — can round-trip.
func genWorkflowJSON(wf agentflow.Workflow) string {
	spec := struct {
		Name        string          `json:"name"`
		Description string          `json:"description"`
		Graph       agentflow.Graph `json:"graph"`
	}{Name: wf.Name, Description: wf.Description, Graph: wf.Graph}
	out, err := json.MarshalIndent(spec, "", "  ")
	if err != nil {
		return "{}"
	}
	return string(out) + "\n"
}

// genPromptPack collects every prompt, model setting, tool schema, and retriever
// config into one Markdown document — the "prompts to go with it" the design is
// built around, ready to paste into any framework.
func genPromptPack(cat *agentflow.Catalog, wf agentflow.Workflow) string {
	defs := cat.Map()
	var b strings.Builder
	fmt.Fprintf(&b, "# %s — Prompt Pack\n\n", orEmpty(wf.Name, "Agentic Workflow"))
	if wf.Description != "" {
		fmt.Fprintf(&b, "%s\n\n", wf.Description)
	}
	b.WriteString("Generated by ScaleForge Agent Studio. One section per node that carries a prompt, model, tool, or retrieval setting.\n\n")

	for _, n := range orderedNodes(wf.Graph) {
		switch n.Type {
		case agentflow.TypeLLM:
			fmt.Fprintf(&b, "## %s — LLM\n\n", displayLabel(n))
			fmt.Fprintf(&b, "- **Model:** `%s`\n- **Temperature:** %.2f\n- **Max tokens:** %d\n\n",
				orEmpty(n.Config.Model, defs[n.Type].DefaultConfig.Model), n.Config.Temperature, n.Config.MaxTokens)
			b.WriteString("**System prompt:**\n\n```\n")
			b.WriteString(orEmpty(n.Config.Prompt, defs[n.Type].DefaultConfig.Prompt))
			b.WriteString("\n```\n\n")
		case agentflow.TypeTool:
			fmt.Fprintf(&b, "## %s — Tool\n\n", displayLabel(n))
			fmt.Fprintf(&b, "- **Name:** `%s`\n\n**Args schema:**\n\n```json\n%s\n```\n\n",
				orEmpty(n.Config.ToolName, "tool"), orEmpty(n.Config.ToolSchema, "{}"))
		case agentflow.TypeRetriever:
			fmt.Fprintf(&b, "## %s — Retriever\n\n", displayLabel(n))
			fmt.Fprintf(&b, "- **Index:** `%s`  **Quantization:** `%s`  **top-k:** %d  **dim:** %d  **corpus:** %d\n\n",
				n.Config.IndexType, n.Config.Quantization, n.Config.TopK, n.Config.Dim, n.Config.CorpusSize)
		case agentflow.TypeRouter:
			fmt.Fprintf(&b, "## %s — Router\n\n- **Condition:** `%s`\n\n", displayLabel(n), orEmpty(n.Config.Condition, "condition"))
		}
	}
	return b.String()
}

func displayLabel(n agentflow.Node) string {
	if n.Label != "" {
		return n.Label
	}
	return n.Type
}

func orEmpty(v, fallback string) string {
	if strings.TrimSpace(v) != "" {
		return v
	}
	return fallback
}
